use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

/// ProofBundle trait — every proof type in axiom-engine implements this.
pub trait ProofBundle: Send + Sync {
    fn proof_type(&self) -> &'static str;
    fn serialize(&self) -> Result<Vec<u8>>;
    fn verify(&self) -> Result<bool>;
    fn commitment(&self) -> [u8; 32];
}

/// Aggregated proof — composition of N ProofBundle instances.
#[derive(Debug, Serialize, Deserialize)]
pub struct AggregatedProof {
    pub components: Vec<ProofComponent>,
    pub aggregate_commitment: [u8; 32],
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ProofComponent {
    pub proof_type: String,
    pub commitment: [u8; 32],
    pub data: Vec<u8>,
}

impl AggregatedProof {
    pub fn new(bundles: Vec<Box<dyn ProofBundle>>) -> Result<Self> {
        let mut components = Vec::new();
        let mut agg = [0u8; 32];
        for b in &bundles {
            let commitment = b.commitment();
            for (i, byte) in commitment.iter().enumerate() {
                agg[i] ^= byte;
            }
            components.push(ProofComponent {
                proof_type: b.proof_type().to_string(),
                commitment,
                data: b.serialize()?,
            });
        }
        Ok(Self {
            components,
            aggregate_commitment: agg,
        })
    }

    pub fn verify_all(&self) -> bool {
        !self.components.is_empty()
    }
}

// ─── RISC Zero integration ────────────────────────────────────────────────

#[cfg(feature = "risc0")]
mod risc0_impl {
    use super::*;
    use risc0_zkvm::{default_prover, ExecutorEnv, Receipt};

    // Generated by build.rs — ELF bytes + image ID of guest
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));

    #[derive(Debug, Serialize, Deserialize)]
    pub struct ComputeInput {
        pub op: String,
        pub data: Vec<f64>,
    }

    #[derive(Debug, Serialize, Deserialize)]
    pub struct ComputeOutput {
        pub op: String,
        pub result: f64,
        pub input_hash: u64,
    }

    pub struct RiscZeroProof {
        pub receipt: Receipt,
        pub output: ComputeOutput,
    }

    impl ProofBundle for RiscZeroProof {
        fn proof_type(&self) -> &'static str {
            "risc-zero-v1"
        }

        fn serialize(&self) -> Result<Vec<u8>> {
            Ok(serde_json::to_vec(&self.output)?)
        }

        fn verify(&self) -> Result<bool> {
            self.receipt
                .verify(AXIOM_GUEST_ID)
                .map(|_| true)
                .map_err(|e| anyhow::anyhow!("receipt verify failed: {}", e))
        }

        fn commitment(&self) -> [u8; 32] {
            let mut out = [0u8; 32];
            out[..8].copy_from_slice(&self.output.input_hash.to_le_bytes());
            out[8..16].copy_from_slice(&self.output.result.to_bits().to_le_bytes());
            out
        }
    }

    pub fn prove(op: &str, data: Vec<f64>) -> Result<RiscZeroProof> {
        let input = ComputeInput {
            op: op.to_string(),
            data,
        };

        let env = ExecutorEnv::builder().write(&input)?.build()?;

        // RISC0_DEV_MODE=1 → instant mock proof (dev/CI)
        // RISC0_DEV_MODE=0 → real STARK proof (~minutes locally, or use Bonsai)
        let receipt = default_prover().prove(env, AXIOM_GUEST_ELF)?.receipt;
        let output: ComputeOutput = receipt.journal.decode()?;

        tracing::info!(op, result = output.result, "ZK proof generated");
        Ok(RiscZeroProof { receipt, output })
    }
}

// ─── Public API ───────────────────────────────────────────────────────────

pub struct ZkProofTool;

impl Default for ZkProofTool {
    fn default() -> Self {
        Self
    }
}

impl ZkProofTool {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate_proof(&self, input: Value) -> Result<Value> {
        let op = input["op"].as_str().unwrap_or("sum");
        let data: Vec<f64> = input["data"]
            .as_array()
            .map(|a| a.iter().filter_map(|v| v.as_f64()).collect())
            .unwrap_or_default();

        #[cfg(feature = "risc0")]
        {
            let proof = risc0_impl::prove(op, data)?;
            let verified = proof.verify()?;
            return Ok(json!({
                "status": "proved",
                "op": op,
                "result": proof.output.result,
                "input_hash": proof.output.input_hash,
                "commitment": hex::encode(proof.commitment()),
                "verified": verified,
                "dev_mode": std::env::var("RISC0_DEV_MODE").unwrap_or_default() == "1"
            }));
        }

        #[allow(unreachable_code)]
        Ok(json!({
            "status": "not_enabled",
            "message": "build with --features risc0 to enable ZK proofs",
            "op": op,
            "data_len": data.len()
        }))
    }
}
